pipeline:
  backend:
    image: golang
    commands:
      - go get
      - go build
      - go test

  frontend:
    image: node:6
    commands:
      - npm install
      - npm test
# branches: master
  telegram:
    image: appleboy/drone-telegram
    # token: xxxxxxxxxx
    # to: telegram_user_id
    secrets: [ token, to ]
    when:
      status: [ success, failure ]
    message: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}