version: "2.1"
services:
  app:
    container_name: web
    # Open shell for local development
    # tty: true
    # stdin_open: true
    # Currently commpose is used for continious integration.
    # So restarts are not needed to detect tests failure.
    # restart: always
    build: .
    ports:
      - "3001:3001"
    volumes:
      # This allows local file changes to be detected by docker container.
      # It is usefull for local development.
      - .:/app
      # Node-sass package throws error without this volume.
      # https://github.com/sass/node-sass/issues/2165#issuecomment-347043659
      - /app/node_modules
    command: "yarn start"
    # links:
    #   - db
    # depends_on:
    #   db:
    #     condition: service_healthy
  # db:
  #   image: mysql
  #   container_name: db
  #   # disable logging output
  #   logging:
  #     driver: none
  #   environment:
  #     - MYSQL_DATABASE=boilerplate_test
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  #   volumes:
  #     - ./data:/data/db
  #   healthcheck:
  #       test: "exit 0"