version: "2.1"
services:
  app:
    container_name: web
    # Open shell for local development
    # tty: true
    # stdin_open: true
    # Currently commpose is used for continious integration.
    # So restarts are not needed to detect tests failure.
    # restart: always
    build: .
    ports:
      - "3001:3001"
    links:
      - db
    # This allows local file changes to be detected by docker container.
    # It is usefull for local development.
    volumes:
      - .:/app/
    depends_on:
      db:
        condition: service_healthy
    command: "yarn start"
  db:
    image: mysql
    container_name: db
    # disable logging output
    logging:
      driver: none
    environment:
      - MYSQL_DATABASE=boilerplate_test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data:/data/db
    healthcheck:
        test: "exit 0"